[package]
name = "email"
version = "0.1.0"
description = "Parse and validate email addresses"
repository = "https://github.com/f0i/email"
keywords = [ "utils,", "email,", "parser" ]
license = "MIT"

[dependencies]
core = "0.6.0"

[toolchain]
moc = "0.15.0"
